# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build

    - name: Gitleaks Scan
      uses: eeveebank/github-actions-gitleaks@1.0.1
      
   
      shell: gitleaks scan -repo =https://github.com/mani7444/k8s-jenkins-aws.git
      
      
      
         # You may pin to the exact commit or the version.
           # uses: eeveebank/github-actions-gitleaks@f83845507ea4e7f181cd2e61f9e7173048cdbfac
     
      
    # Look behind depth
     












